{
 "title": "Datavolo Runtime Overview",
 "description": "A quick overview of the flow running in a Datavolo Runtime, powered by Apache NiFi.",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Datavolo Runtime - JVM Performance",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }
  },
  {
   "title": "Heap Used",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "jvm_memory_heap_usage_percentage",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Non-Heap Usage",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "jvm_memory_non_heap_usage_percentage",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Active Threads",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 6, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "jvm_threads_count_thread", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Thread Deadlocks",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 9, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "jvm_threads_deadlocks_thread", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Active Threads",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 1 },
   "targets": [
    { "expr": "jvm_threads_count_thread", "legendFormat": "Active Threads" }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "jvm_uptime_second", "legendFormat": "__auto" }
   ]
  },
  { "title": "Datavolo Runtime - Processors", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "Processors - Input Size (Last 5 Minutes) - Top 10",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "expr": "topk(10, processor_input_content_size_byte) / 1000000",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Total FlowFiles Removed (Last 5 Minutes)",
   "type": "stat",
   "description": "This many files have been fully processed and dropped by the flow at some point in the last 5 minutes.",
   "gridPos": { "h": 8, "w": 5, "x": 7, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(processor_flowfiles_removed)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Running Processors",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(processor_run_status_running)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Processor Status",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 8 },
   "targets": [
    {
     "expr": "sum(processor_run_status_validating)",
     "legendFormat": "Validating"
    },
    {
     "expr": "sum(processor_run_status_invalid)",
     "legendFormat": "Invalid"
    },
    {
     "expr": "sum(processor_run_status_disabled)",
     "legendFormat": "Disabled"
    },
    {
     "expr": "sum(processor_run_status_stopped)",
     "legendFormat": "Stopped"
    },
    {
     "expr": "sum(processor_run_status_running)",
     "legendFormat": "Running"
    }
   ]
  },
  {
   "title": "Slowest 5 Processors",
   "type": "timeseries",
   "description": "Slowness is determined by the average time the processor spends on a task. Time in milliseconds.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "topk(5, (processor_time_processing_nanosecond / processor_input_count_item) / 1000000)",
     "legendFormat": "{{name}} {{id}}"
    }
   ]
  },
  {
   "title": "Fastest 5 Processors",
   "type": "timeseries",
   "description": "Speed is determined by the average time the processor spends on a task when it is Running. Time in milliseconds.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "bottomk(5, (processor_time_processing_nanosecond / processor_input_count_item) / 1000000)",
     "legendFormat": "{{name}} {{id}}"
    }
   ]
  },
  { "title": "Datavolo Runtime - Connections", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "Longest Queued Duration",
   "type": "table",
   "description": "Connections with FlowFiles that have been queued for the longest time may indicate a problem with the flow or a particular piece of data.",
   "gridPos": { "h": 16, "w": 7, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "topk(10, last_over_time(connection_queued_duration_max_millisecond[$__interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Queued FlowFiles",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 7, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(connection_queued_count_item)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Number of FlowFiles Queued",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "targets": [
    {
     "expr": "sum(connection_queued_count_item)",
     "legendFormat": "Total Queued Count"
    }
   ]
  },
  {
   "title": "Total Queued Data",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 7, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(connection_queued_bytes_byte)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Data Size Queued",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(connection_queued_bytes_byte)",
     "legendFormat": "Total Size Queued"
    }
   ]
  }
 ]
}