# ============================================
# PRODUCTION CONFIGURATION - FULL mTLS
# ============================================

# Main TCP listener with mTLS

listener "unix" {
  address = "/vault/vault.sock"
  socket_mode = "0600"
  tls_disable = true
}

listener "tcp" {
  address = "0.0.0.0:8200"
  cluster_address = "0.0.0.0:8201"
  
  # Server certificates (will be generated by PKI)
  tls_cert_file = "/certs/vault/server.crt"
  tls_key_file = "/certs/vault/server.key"
  
  # Client CA for mTLS (all clients must present certs signed by this)
  tls_require_and_verify_client_cert  = "false"
  
  # TLS settings
  tls_min_version = "tls12"
  tls_cipher_suites = "TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384"
}

# Storage backend (same as bootstrap)
storage "raft" {
  path = "/vault/data"
  node_id = "node1"
}

# Telemetry
telemetry {
  prometheus_retention_time = "24h"
  disable_hostname = true
}

# API and cluster addresses
api_addr = "https://vault.trading.local:8200"
cluster_addr = "https://vault.trading.local:8201"

# Enable UI (optional)
ui = true

# Log level
log_level = "info"

# Disable mlock in containers (adjust based on your setup)
disable_mlock = false